# -*- coding: utf-8 -*-
"""A02 Add MLPRegressor with early stopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8KeMO0fcbINJCGWAmu40_7t8shdONkb
"""

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

def load_and_split(test_size=0.2, random_state=42):
    """Load California Housing dataset and split into train/test."""
    housing = fetch_california_housing()
    X, y = housing.data, housing.target
    feature_names = list(housing.feature_names)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )

    print(f"Dataset loaded: {X.shape[0]} samples, {X.shape[1]} features")
    print(f"Features: {feature_names}")
    print(f"Train: {X_train.shape[0]}  |  Test: {X_test.shape[0]}")
    return X_train, X_test, y_train, y_test, feature_names

if __name__ == "__main__":
    load_and_split()

from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

def build_and_train():
    """Train an MLPRegressor with early stopping on California Housing data."""
    X_train, X_test, y_train, y_test, _ = load_and_split()

    # Scale features — critical for MLPRegressor convergence
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    model = MLPRegressor(
        hidden_layer_sizes=(128, 64, 32),  # custom: 3-layer network
        alpha=0.001,                        # custom: L2 regularization
        learning_rate_init=0.005,           # custom: initial learning rate
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=15,
        max_iter=500,
        random_state=42,
    )

    model.fit(X_train_scaled, y_train)
    print(f"Stopped after {model.n_iter_} iterations")
    print(f"Best validation score: {model.best_validation_score_:.4f}")

    return model, scaler, X_train_scaled, X_test_scaled, y_train, y_test

if __name__ == "__main__":
    build_and_train()