# -*- coding: utf-8 -*-
"""A02 Add test predictions + plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8KeMO0fcbINJCGWAmu40_7t8shdONkb
"""

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

def load_and_split(test_size=0.2, random_state=42):
    """Load California Housing dataset and split into train/test."""
    housing = fetch_california_housing()
    X, y = housing.data, housing.target
    feature_names = list(housing.feature_names)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )

    print(f"Dataset loaded: {X.shape[0]} samples, {X.shape[1]} features")
    print(f"Features: {feature_names}")
    print(f"Train: {X_train.shape[0]}  |  Test: {X_test.shape[0]}")
    return X_train, X_test, y_train, y_test, feature_names

if __name__ == "__main__":
    load_and_split()

from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

def build_and_train():
    """Train an MLPRegressor with early stopping on California Housing data."""
    X_train, X_test, y_train, y_test, _ = load_and_split()

    # Scale features — critical for MLPRegressor convergence
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    model = MLPRegressor(
        hidden_layer_sizes=(128, 64, 32),  # custom: 3-layer network
        alpha=0.001,                        # custom: L2 regularization
        learning_rate_init=0.005,           # custom: initial learning rate
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=15,
        max_iter=500,
        random_state=42,
    )

    model.fit(X_train_scaled, y_train)
    print(f"Stopped after {model.n_iter_} iterations")
    print(f"Best validation score: {model.best_validation_score_:.4f}")

    return model, scaler, X_train_scaled, X_test_scaled, y_train, y_test

if __name__ == "__main__":
    build_and_train()

import matplotlib.pyplot as plt
import numpy as np

def plot_train_predictions(model, X_train_scaled, y_train, save_path="plot_train.png"):
    y_pred = model.predict(X_train_scaled)
    r2   = 1 - np.sum((y_train - y_pred)**2) / np.sum((y_train - np.mean(y_train))**2)
    rmse = np.sqrt(np.mean((y_train - y_pred)**2))

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.scatter(y_train, y_pred, alpha=0.3, s=12, color="#2563EB", label="Samples")
    lo, hi = min(y_train.min(), y_pred.min()), max(y_train.max(), y_pred.max())
    ax.plot([lo, hi], [lo, hi], "r--", linewidth=1.5, label="Perfect fit")
    ax.set_xlabel("Actual Price (100k USD)")
    ax.set_ylabel("Predicted Price (100k USD)")
    ax.set_title(f"Actual vs. Predicted — Train Set\nR²={r2:.4f}  RMSE={rmse:.4f}")
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Saved: {save_path}")

if __name__ == "__main__":
    model, scaler, X_train_s, X_test_s, y_train, y_test = build_and_train()
    plot_train_predictions(model, X_train_s, y_train)

from IPython.display import Image, display
display(Image("plot_train.png"))

import matplotlib.pyplot as plt
import numpy as np

def plot_test_predictions(model, X_test_scaled, y_test, save_path="plot_test.png"):
    y_pred = model.predict(X_test_scaled)
    r2   = 1 - np.sum((y_test - y_pred)**2) / np.sum((y_test - np.mean(y_test))**2)
    rmse = np.sqrt(np.mean((y_test - y_pred)**2))

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.scatter(y_test, y_pred, alpha=0.4, s=14, color="#16A34A", label="Samples")
    lo, hi = min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())
    ax.plot([lo, hi], [lo, hi], "r--", linewidth=1.5, label="Perfect fit")
    ax.set_xlabel("Actual Price (100k USD)")
    ax.set_ylabel("Predicted Price (100k USD)")
    ax.set_title(f"Actual vs. Predicted — Test Set\nR²={r2:.4f}  RMSE={rmse:.4f}")
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Saved: {save_path}")

if __name__ == "__main__":
    model, scaler, X_train_s, X_test_s, y_train, y_test = build_and_train()
    plot_test_predictions(model, X_test_s, y_test)

from IPython.display import Image, display
display(Image("plot_test.png"))